### ISSUE TITLE
Peer dependency issue

### ISSUE THREAD

**Issue by vanillaike** [lanceschi/threejs-ply-loader#11]
Hi,

There's a peer dependency on three at version ^0.115.1. I'm not sure if three removed that version or if it's a typo but 0.115.1 doesn't exist. Can this peer be downgraded to 0.115.0, or upgraded to 0.116.1?

Please let me know If I should create a PR for this and I'll try to get to it as soon as I can.

**Comment by lanceschi** [comment]
Hi @vanillaike most probably a typo. Fixed that and made a new release. Thanks for pointing that out.

https://github.com/lanceschi/threejs-ply-loader/blob/1.1.9/CHANGELOG.md#v119---2020-05-08
