### ISSUE TITLE
Will this work with node 10?

### ISSUE THREAD

**Issue by jklmli** [lanceschi/threejs-ply-loader#13]
Trying to use this, but stuck on an older version of Node (v10.19.0)

Would it be possible to update the package.json to require Node >= 10?  Does this use any features specific to Node 12?

**Comment by lanceschi** [comment]
Hi @jiaweihli thanks for reaching out, it does make sense and most probably it will work flawlessly with Node `v10.x.x`. I made a quick try and tests are passing. I set node engine version to `>=10.0.0`and released [threejs-ply-loader v1.1.10][1].


https://github.com/lanceschi/threejs-ply-loader/blob/develop/CHANGELOG.md#v1110---2020-05-29


[1]: https://www.npmjs.com/package/threejs-ply-loader/v/1.1.10

**Comment by jklmli** [comment]
Great, thank you for doing this so quickly!
